### ISSUE TITLE
【2.2.2】如果图片无法加载，界面将卡住，并且不能通过返回键返回

### ISSUE THREAD

**Issue by jhdjks** [yangchaojiang/ZoomPreviewPicture#100]
如题，2.1.8就有这个问题了，今天升级了2.2.2还是不行

**Comment by jhdjks** [comment]
设置了占位和错误的默认图也不行，图片确实是不可以访问的，url路径都不对，但是不希望卡住不能操作

**Comment by yangchaojiang** [comment]
你使用哪个图片加载框架哦

**Comment by jhdjks** [comment]
> 你使用哪个图片加载框架哦

Glide

**Comment by jhdjks** [comment]
IZoomMediaLoader实现：

![image](https://user-images.githubusercontent.com/15992115/54170549-1ba24e80-44b2-11e9-9003-0d2e7229e6fe.png)

**Comment by yangchaojiang** [comment]
版本多少哦

**Comment by jhdjks** [comment]
使用：

![image](https://user-images.githubusercontent.com/15992115/54170613-599f7280-44b2-11e9-99a1-7f885f358ce5.png)

**Comment by jhdjks** [comment]
Glide:3.7.0
ImagePreview:2.2.2

**Comment by yangchaojiang** [comment]
Glide:3.7.0  升级试一下

**Comment by jhdjks** [comment]
其他项目用的最新版本的Glide，也有这个问题。

或者是不是onLoadFailed这个方法我的实现有问题

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/54170990-cf580e00-44b3-11e9-95ea-53d4f9c109f0.png)

**Comment by yangchaojiang** [comment]
不需要判断吧

**Comment by jhdjks** [comment]
我改下试试哈

**Comment by yangchaojiang** [comment]
好的

**Comment by jhdjks** [comment]
我找到原因了，我想让失败的图片也能像成功的图片那样子滑动返回，所以在onLoadFailed这个方法里面
手动调用了onResourceReady，但没走这句代码。界面卡死是因为simpleTarget.onLoadFailed(null)这里设置了null导致的。。。我改成了现在这样就行了，而且可以滑动关闭，主要是因为2.2.2能拿到imageView控件对象了，2.1.8拿不到才那么写的

![image](https://user-images.githubusercontent.com/15992115/54171774-940b0e80-44b6-11e9-8b8d-b250b656c195.png)

**Comment by yangchaojiang** [comment]
恩恩。之前版本没有考虑到应该把 imageView暴露出来。也是我的失误。！buhaoysi

**Comment by jhdjks** [comment]
☆(￣▽￣)/$:*这个框架好用，五星好评

**Comment by yangchaojiang** [comment]
谢谢支持啦
