### ISSUE TITLE
关于自定义activity

### ISSUE THREAD

**Issue by chenxi0203** [yangchaojiang/ZoomPreviewPicture#101]
想问下自定义activity中能否实现图片预览效果，不是基于：GPreviewBuilder.from(getActivity()).setData(mDisplayList) .setCurrentIndex(position).setSingleFling(true) .setType(GPreviewBuilder.IndicatorType.Number) .start(); 这种方式触发，正常的activity跳转，跳转后的activity能实现图片预览及缩放功能，多张图片左右切换。

**Comment by yangchaojiang** [comment]
不建议这么做，自定义的把你activity.class 放在。form方法就行了

**Comment by chenxi0203** [comment]
> 不建议这么做，自定义的把你activity.class 放在。form方法就行了

form方法？能详细说下具体怎么实现嘛，应为我这边不是点击九宫格中图片实现预览，而是基于比如某个按钮触发显示的。   还咨询个问题，我基于demo提供的方式自定义activity，每次跳转到这个预览activity时会有个白屏的过渡，这个怎么解决？

**Comment by yangchaojiang** [comment]
把你的activity 主题设置透明  你的activity主题没有设置。请查看demo的自定义activity

**Comment by chenxi0203** [comment]
> 把你的activity 主题设置透明 你的activity主题没有设置。请查看demo的自定义activity

就是对着demo那样做的，demo中的自定义预览activity  CustomActivity也有这个问题，进入这个预览activity中间就会有白屏的过渡

**Comment by chenxi0203** [comment]
而且demo中自定义activity退出预览时状态栏闪烁。

**Comment by yangchaojiang** [comment]
这个是系统问题。这个都是系统api操作
