### ISSUE TITLE
横屏放大后跟竖屏放大一个效果，拉伸过大

### ISSUE THREAD

**Issue by SeanSMh** [yangchaojiang/ZoomPreviewPicture#102]
横屏放大后跟竖屏放大一个效果，拉伸过大，跟demo横屏预览不一样，请问怎么解决

**Comment by yangchaojiang** [comment]
不支持横屏

**Comment by SeanSMh** [comment]
我想跟demo一样，横屏时，显示小图片（也就是横屏没有放大效果），但是我这个横屏时放大了，不知道怎么办？

**Comment by yangchaojiang** [comment]
截图看一下

**Comment by SeanSMh** [comment]
![横屏截图](https://user-images.githubusercontent.com/34102479/54249934-ddbe2c80-457c-11e9-8068-7752e6fd4f4a.png)
Demo里的转横屏是这样的效果，我想实现这样的效果来着
