### ISSUE TITLE
如下所示，跟竖屏效果一样了，屏幕还放不下

### ISSUE THREAD

**Issue by SeanSMh** [yangchaojiang/ZoomPreviewPicture#103]
![横屏截图](https://user-images.githubusercontent.com/34102479/54249642-e6623300-457b-11e9-9035-494088fe3c01.png)

**Comment by yangchaojiang** [comment]
麻烦不要新开问题

**Comment by yangchaojiang** [comment]
都说不支持横屏，横屏高宽计算不一样的

**Comment by SeanSMh** [comment]
Demo横屏效果是这样的，我想实现这样的效果来着
![横屏截图](https://user-images.githubusercontent.com/34102479/54250094-5f15bf00-457d-11e9-8e08-3da40ce36759.png)

**Comment by SeanSMh** [comment]
已解决，去掉了自定义ImageLoader类的Glide options的一些设置，ClearMomory()方法里按照demo里那样写。

**Comment by yangchaojiang** [comment]
好的
