### ISSUE TITLE
当图片超出屏幕显示的数量时, 返回没有自动滚动定位到目标图片的位置,直接是返回左上角的效果

### ISSUE THREAD

**Issue by guoq1** [yangchaojiang/ZoomPreviewPicture#108]
使用recycle 时候, computeBoundsBackward() 方法只能作用于同一屏幕内的返回位置, 当图片特别多,viewpager滑动到十几张图片超出屏幕承载的图片数量后, 没有自动滚动到目标位置,然后缩小图片到目标位置动画, 希望解决一下

**Comment by yangchaojiang** [comment]
打开预览后  滑到超出屏幕的的图片  列表不存在图片的位置，无法计算的！
能还原的图片 都是获取列表显示的图片渲染位置

**Comment by guoq1** [comment]
我有个思路你看看能行吗, viewpager切换或者返回的时候把 currentIndex 传回去, 先让recycleView.smoothScrollToPosition(currentIndex); 然后重新计算一下滚动后layoutmanager所见范围的 Rect, 在执行返回动画定位缩放动画过去

**Comment by yangchaojiang** [comment]
不行的，前面没有渲染view的

**Comment by yangchaojiang** [comment]
懂了吧。
