### ISSUE TITLE
建议适配androidx

### ISSUE THREAD

**Issue by yinlipeng** [yangchaojiang/ZoomPreviewPicture#111]

**Comment by yangchaojiang** [comment]
androidx  有使用上有什么问题么

**Comment by qiangqiangs** [comment]
注意哈这一行代码，不加会报错 
protected UserViewInfo(Parcel in) {
        this.url = in.readString();
        this.mBounds = in.readParcelable(Rect.class.getClassLoader());
        this.user = in.readString();
        this.videoUrl = in.readString();
    }

**Comment by yangchaojiang** [comment]
可以 谢谢建议啦 明天我提交一下

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/61289908-1442d700-a7fd-11e9-8386-1e674f667827.png)

**Comment by yangchaojiang** [comment]
你的实现没有这个方法吗 。我是插件生成的

**Comment by qiangqiangs** [comment]
我是自己弄得实体类，要求实现这个类的write那个方法，里面需要声明变量，序列化的问题，对了，图片全屏支持自适应吗？图片大了显示不完



------------------ 原始邮件 ------------------
发件人: "yangchaojiang"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 晚上7:09
收件人: "yangchaojiang/ZoomPreviewPicture"<ZoomPreviewPicture@noreply.github.com>; 
抄送: "强强"<824364975@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yangchaojiang/ZoomPreviewPicture] 建议适配androidx (#111)




你的实现没有这个方法吗 。我是插件生成的

**Comment by qiangqiangs** [comment]
就像这样，放大后，显示不全，建议等比例放大
------------------ 原始邮件 ------------------
发件人: "yangchaojiang"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 晚上7:09
收件人: "yangchaojiang/ZoomPreviewPicture"<ZoomPreviewPicture@noreply.github.com>;
抄送: "强强"<824364975@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yangchaojiang/ZoomPreviewPicture] 建议适配androidx (#111)




你的实现没有这个方法吗 。我是插件生成的

**Comment by yangchaojiang** [comment]
实体类，实现接口后，必须在自己实体类，必须重新写方法的

**Comment by yangchaojiang** [comment]
类库方法都是抽象的。需要自己实现的，
你可以demo的实体类

**Comment by qiangqiangs** [comment]
可以了，图片大了显示不完全，建议等比例放大




------------------ 原始邮件 ------------------
发件人: "yangchaojiang"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 晚上7:16
收件人: "yangchaojiang/ZoomPreviewPicture"<ZoomPreviewPicture@noreply.github.com>; 
抄送: "强强"<824364975@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yangchaojiang/ZoomPreviewPicture] 建议适配androidx (#111)




类库方法都是抽象的。需要自己实现的，
 你可以demo的实体类

**Comment by yangchaojiang** [comment]
图片加载大小和图片
完全自己控制！
就是你加载图片加载框架决定，
对图片缩放处理，本库不会图片显示进行处理的

**Comment by qiangqiangs** [comment]
好的，那我看看




------------------ 原始邮件 ------------------
发件人: "yangchaojiang"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 晚上7:20
收件人: "yangchaojiang/ZoomPreviewPicture"<ZoomPreviewPicture@noreply.github.com>; 
抄送: "强强"<824364975@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [yangchaojiang/ZoomPreviewPicture] 建议适配androidx (#111)




图片加载大小和图片
 完全自己控制！
 就是你加载图片加载框架决定，
 对图片缩放处理，本库不会图片显示进行处理的

**Comment by yangchaojiang** [comment]
图片不全应该有的！你可以demo自定义的framgent。拿到imagevirw控件，进行图片操作

**Comment by qiangqiangs** [comment]
glide的centerinside解决了，小一点，能看清楚，建议更新demo glide版本
