### ISSUE TITLE
targetSdkVersion = 28 图片加载失败的时候，错误图片放大会发生抖动，退出时ViewPager滑动

### ISSUE THREAD

**Issue by zmemo** [yangchaojiang/ZoomPreviewPicture#114]
版本2.2.3  拉下来的示例代码
修改项目gradle 
```
project.ext {
        compileSdkVersion=28
        targetSdkVersion=28
        // 27正常 28会发生抖动
        //targetSdkVersion=27
        ...
    } 
```
点击放大会先放到到中间偏右 然后缩放一点回到中间 

之前有提交一个issue
点击退出时候快速向右滑动 会出现上一张图片 设置enable不起作用 需要设置ViewPager滑动阻拦
setEnable(false) -->setScollable(false)
setEnable(true)去掉
```
    override fun onTouchEvent(ev: MotionEvent): Boolean {
        return isCanScrollable && super.onTouchEvent(ev)
    }

    override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {
        return try {
            isCanScrollable && super.onInterceptTouchEvent(ev)
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }
```

![95A815561CE6C7AEE22E8FF088403DC1](https://user-images.githubusercontent.com/23187679/60429909-a9a37000-9c2e-11e9-9ea9-d570f2f5bb5f.gif)

**Comment by yangchaojiang** [comment]
我改28了 没有复现这个情况。

**Comment by zmemo** [comment]
在全面屏手机上或导航栏在屏幕内容范围内的手机上测试会出现如上gif图展示图片抖动清空
在底部有三导航或者导航栏在底部黑色不可用区域 不会出现这个问题
退出滑动问题依旧存在

**Comment by yangchaojiang** [comment]
导航或者导航栏在底部黑色不可用区域 不会出现这个问题  
自己定义activity 主题风格

**Comment by zmemo** [comment]
使用了自定义的Activity 主题为透明无标题
```   
 <activity
            android:name=".preview.ImagePreviewActivity"
            android:screenOrientation="portrait"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" />
```

**Comment by zmemo** [comment]
还有一个问题 在图片放大的时候连点 会导致崩溃
没有去深入研究 只是暂时解决了问题
```
    private float moveScale() {
        if (markTransform == null) {
            initTransform();
        }
        // 设置默认
        if (markTransform == null) {
            return 0f;
        }
        return Math.abs(getTop() / markTransform.height);
    }
```

**Comment by yangchaojiang** [comment]
应该是使用对应放大的图片库 bug  引用那个库版本3.0版本。

**Comment by yangchaojiang** [comment]
有错误日志吗

**Comment by zmemo** [comment]
> 有错误日志吗

崩溃只出现一次 偶发性的 后面出不来了 只记得是空指针 markTransform为null

然后主题的问题解决了（只针对错误图） 如果只设置一套xhdpi错误图 放大会有出现上方gif图问题 我设置了mdpi到xxxhdpi 五套图就不会出现这种问题了 

2.2.5的退出滑动还是问题 下载代码手动改了 设置ViewPager设置enable不起作用 还是需要拦截滑动事件

**Comment by yangchaojiang** [comment]
一般都资源配全图，你有文件夹，没有图片，由系统分配查找对应的图片。
2.2.5 可能有点麻烦，我也在看

**Comment by yangchaojiang** [comment]
```
 implementation 'com.ycjiang:ImagePreview:2.2.6-beta1'
```
 看看还有问题么

**Comment by zmemo** [comment]
使用2.2.6后 
1、双指放大 图片会突然抖动移动位置
2、放大后图片 开启手势滑动退出 手指向下滑动会直接启动滑动退出 实际应该是展示放大后上方未显示的部分 滑动到图片顶部 之后才是手势退出
![111 (1)](https://user-images.githubusercontent.com/23187679/64662075-b12a9500-d479-11e9-80e2-46580036c70a.gif)

**Comment by yangchaojiang** [comment]
你的gif 拉动的距离  太小的  没有达到的零界点
