### ISSUE TITLE
一直有个加载进度圈怎么停止， picasso 怎么实现onStop， clearMemory

### ISSUE THREAD

**Issue by nirvana72** [yangchaojiang/ZoomPreviewPicture#119]
我图片展示过程中， 中间一直有个加载进度圈， 在哪里停止
![image](https://user-images.githubusercontent.com/15214079/63159465-358e2180-c04e-11e9-926f-0a462b38bcb1.png)

另外我用的是 picasso 加载网络图片 
![image](https://user-images.githubusercontent.com/15214079/63159526-548cb380-c04e-11e9-901b-b29cbcd63bb5.png)
相应的 onStop， clearMemory 应该实现些什么呢， 
现在什么都没写， 错是不报， 但会不会内存过量啊

**Comment by yangchaojiang** [comment]
picasso 加载库没有相相应的，可以不写
你加载成功了，回调给我通知我，你就会回调对象p3

**Comment by fansonq** [comment]
请问你解决了吗？我的也存在loading动画不消失的问题；

**Comment by yangchaojiang** [comment]
回调对象，你手动手动调一下，回调对象  p3 @fansonq

**Comment by yangchaojiang** [comment]
p3 参数是有用的
