### ISSUE TITLE
组图情况下，左右滑动后，退出动画永远会回到初始点开图片的位置

### ISSUE THREAD

**Issue by elmliu** [yangchaojiang/ZoomPreviewPicture#122]
![S90909-13591949](https://user-images.githubusercontent.com/35032015/64506633-3cd5e180-d313-11e9-8c28-783532af9c6b.gif)
这个GIF的压缩比较严重，就是我点开第一张图，划到第三张，然后不管拖拽或是点击返回键，退出动画都是会回到刚开始点开图片的第一张的位置，按理应该回到第三张的位置<br/>
没有用自定义Activity和Fragment. <br/>
原始图片位置信息是由```computeBoundsBackwards()```得到并传入的，我有个问题是，在fragment左右切换的时候，会再使用它进行原始图片位置信息的更新吗？或者说类似的逻辑在什么位置呢，感谢回复！

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/64509883-4d865780-d313-11e9-88f3-2fdd722dd524.png)
 看你的gif 调用缺少核心方法。

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/64509965-89b9b800-d313-11e9-8d2e-4698f11defa1.png)

**Comment by elmliu** [comment]
@yangchaojiang
感谢回复，问题解决了！

**Comment by yangchaojiang** [comment]
谢谢支持
