### ISSUE TITLE
2.2.6和最新的beta1都试了，全都有问题，很严重

### ISSUE THREAD

**Issue by yucaigitup** [yangchaojiang/ZoomPreviewPicture#123]
2个严重bug
1. .setDrag(false) 时，图片双指放大和缩小后松开手，图片会抖动，很严重
2.setDrag(true)时，图片双指放大缩小不会抖动，但是图片加载不全，这个也太严重了，左右两侧丢失严重 

图片拉伸库建议使用 implementation 'com.bm.photoview:library:1.4.1'

**Comment by yangchaojiang** [comment]
图片加载不全 本库没有关系。加载都是图片框架。 本库核心图片移动

**Comment by yucaigitup** [comment]
嗯，我知道，移动部分，做的非常不错，我只是提供我发现的bug，再次感谢

**Comment by yangchaojiang** [comment]
那你暂时使用2.2.5

**Comment by bailandi** [comment]
加载不全是因为Demo里加载的使用用了centerCrop
