### ISSUE TITLE
图片laoding过程中无法点击返回

### ISSUE THREAD

**Issue by caiyoufei** [yangchaojiang/ZoomPreviewPicture#124]
手机：魅蓝5s
lib版本：2.2.6
前置条件：列表中的图片展示用的SketchImageView，IZoomMediaLoader用的glide加载
问题描述：
1.由于图片太大，所以loading时间会比较长，在loading的时候，整个页面是透明的，因此在原来的页面上可以看到中间显示一个loading图，点击返回和其他操作都无效，必须等待图片加载出结果，如下图：
![loading中无法返回](https://user-images.githubusercontent.com/11989916/66251200-c1334d00-e777-11e9-8e92-517642ee0352.gif)
2.如果打开的是多张图片，点开后同问题1处于loading状态，但是可以左右切换，切换的图片如果已经加载完成了，是可以拖动图片的，原本拖到底部会关闭图片预览，但是由于点击打开的图片一直没有加载完成，所以拖动释放后，图片会卡在释放的地方(由于不好重新，我模拟一下现象)，如下图：
![loading过程中切换到另外位置加载完成后拖拽释放后导致卡在释放处](https://user-images.githubusercontent.com/11989916/66251328-29366300-e779-11e9-9fea-bb5dd87b618d.gif)
3.在laoding过程中切换图片，点击返回按钮，会导致黑色的背景消失变成透明，如下图：
![loading中点击返回导致黑色背景消失](https://user-images.githubusercontent.com/11989916/66251249-91387980-e778-11e9-840a-8f44ee507c58.gif)

**Comment by yangchaojiang** [comment]
请不要列表上加载原图 谢谢

**Comment by chengww5217** [comment]
遇到同样的问题，我觉得不是原图的问题吧，考虑到手机网路的不确定性，在网络不佳的情况下也很容易出这个情况。

临时的解决办法：

1. 尝试重写 `onBackPressed()` 方法，是可以返回，但是所有按返回键返回的动画没有了，即使图片已经加载的时候。

2. 尝试在自定义的 ImageLoad： `GlideImageLoader` 中添加一个很小的透明 placeholder：
`GlideApp.with(context).asBitmap().load(path).placeholder(R.mipmap.ic_transparent).error(R.mipmap.load_image_error)...`
可以正常返回，但是仅在加载中的返回动画没有了。

----

我觉得还是让加载中可以正常返回会比较好。
