### ISSUE TITLE
导入之后点击大图一直报错

### ISSUE THREAD

**Issue by nanfeifei** [yangchaojiang/ZoomPreviewPicture#125]
java.lang.IllegalArgumentException: width and height must be > 0
报错内容提示这个，运行你Demo是正常的，不知道哪里的问题，我把你项目的Glide升级成4.8.0，suport包升级成了androidx，跟我的一样了，但是你的还是正常，我的还是报这个错，图片地址也没问题，不知道哪里有问题。。

**Comment by yangchaojiang** [comment]
请不要类库的版本做升级处理哦
