### ISSUE TITLE
有没有什么方法可以向自定义的activity传递一些额外的数据呢

### ISSUE THREAD

**Issue by hurist** [yangchaojiang/ZoomPreviewPicture#127]
作者大大你好，假如说自己自定义了一个activity，除了展示图片本身外，还要展示这组图片额外的一些信息，要怎么做呢，感觉要是在每一个图片信息实体类里都放一个又不太合理，有什么方法把这部分信息传递给自己自定义的这个activity呢

**Comment by chengww5217** [comment]
可以通过反射拿到 GPreviewBuilder 中的 Intent 对象，往 Intent 对象内 put values

```java
GPreviewBuilder gPreviewBuilder = GPreviewBuilder.from(activity)
                .to(PreviewImageActivity.class)
                .setData(imageMsgContents)
                .setUserFragment(PreviewImageFragment.class)
                .setFullscreen(true)
                .setCurrentIndex(currentIndex)
                .setSingleShowType(false)
                .setSingleFling(false)
                .setDrag(false)
                .setType(GPreviewBuilder.IndicatorType.Number);
// 反射获取 Intent
try {
            Field intentFiled = gPreviewBuilder.getClass().getDeclaredField("intent");
            intentFiled.setAccessible(true);
            Object o = intentFiled.get(gPreviewBuilder);
            if (o instanceof Intent) {
                Intent intent = (Intent) o;
                intent.putExtra("test", "A test value");
            }
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }

gPreviewBuilder.start();
```

然后去你重写的 activity 中取值：

```java
        String test = getIntent().getStringExtra("test");
        Log.d("Intent-test", test);
```

**Comment by yangchaojiang** [comment]
你是操作每个实体类数据 ，你应该自定义是Fragment类。每个实体类对应的 实现我的接口的实体类，
整个实体类，你可以加任意的字段

**Comment by hurist** [comment]
> 可以通过反射拿到 GPreviewBuilder 中的 Intent 对象，往 Intent 对象内 put values
> 
> ```java
> GPreviewBuilder gPreviewBuilder = GPreviewBuilder.from(activity)
>                 .to(PreviewImageActivity.class)
>                 .setData(imageMsgContents)
>                 .setUserFragment(PreviewImageFragment.class)
>                 .setFullscreen(true)
>                 .setCurrentIndex(currentIndex)
>                 .setSingleShowType(false)
>                 .setSingleFling(false)
>                 .setDrag(false)
>                 .setType(GPreviewBuilder.IndicatorType.Number);
> // 反射获取 Intent
> try {
>             Field intentFiled = gPreviewBuilder.getClass().getDeclaredField("intent");
>             intentFiled.setAccessible(true);
>             Object o = intentFiled.get(gPreviewBuilder);
>             if (o instanceof Intent) {
>                 Intent intent = (Intent) o;
>                 intent.putExtra("test", "A test value");
>             }
>         } catch (NoSuchFieldException | IllegalAccessException e) {
>             e.printStackTrace();
>         }
> 
> gPreviewBuilder.start();
> ```
> 
> 然后去你重写的 activity 中取值：
> 
> ```java
>         String test = getIntent().getStringExtra("test");
>         Log.d("Intent-test", test);
> ```

了解，忘了可以反射了，谢谢

**Comment by hurist** [comment]
> 你是操作每个实体类数据 ，你应该自定义是Fragment类。每个实体类对应的 实现我的接口的实体类，
> 整个实体类，你可以加任意的字段

我想过这种，但主要我这边的场景是一个带多张图片的动态，点击图片以后就可以展示大图，然后还会在activity中展示部分动态的信息，按照你的那种方法来的话每个fragment都会带上完整的全部信息，感觉不太好

**Comment by yangchaojiang** [comment]
activity 的中 列表数据哦

**Comment by hurist** [comment]
> activity 的中 列表数据哦

差不多就是那意思，有点像手机qq的动态图片点开的那种，我觉得可以开放一下这个，不然自定义activity的意义不大呢，又没办法通过常规渠道给activity传递数据，就只能改改界面
