### ISSUE TITLE
点击图片放大问题！

### ISSUE THREAD

**Issue by cbuemc** [yangchaojiang/ZoomPreviewPicture#129]
我是用的自己的recyclerview做成九宫格样式，点击图片时，老是会先弹出先取一部分放大的残影，闪一下加载好就显示正常，拖拽返回时好像也有类似的问题，单图显示比较明显，这个是什么原因造成的？

**Comment by yangchaojiang** [comment]
看dmeo

**Comment by yangchaojiang** [comment]
九宫格样式  也是用其他作者开源库， 不是我做的
