### ISSUE TITLE
请教一下 视频播放 点击没有效果VideoView 也无法预览

### ISSUE THREAD

**Issue by Danniel-yan** [yangchaojiang/ZoomPreviewPicture#133]

**Comment by yangchaojiang** [comment]
demo 不行吗

**Comment by Danniel-yan** [comment]
> demo 不行吗

嗯嗯 不可以 感觉播放视频的调用方式不对😅

**Comment by yangchaojiang** [comment]
demo 是可以的

**Comment by Danniel-yan** [comment]
> demo 是可以的

难道我看的是假的demo😅

**Comment by Danniel-yan** [comment]
> demo 是可以的

在调用的地方直接这么写就可以吗？传递一个url参数
  val intent = Intent(baseContext, VideoPlayerDetailedActivity::class.java)
    intent.putExtra("url", "http://lmp4.vjshi.com/2017-09-13/f55a900d89679ac1c9837d5b5aaf632a.mp4")
                                startActivity(intent)

**Comment by yangchaojiang** [comment]
不能

**Comment by yangchaojiang** [comment]
参考demo 使用api 呀 看一下说明
