### ISSUE TITLE
全屏图拖拽返回困难啊

### ISSUE THREAD

**Issue by INTKILOW** [yangchaojiang/ZoomPreviewPicture#136]
能不能设置拖拽多偏移量就返回，拖拽返回偏移量太大了，导致拖拽返回不太灵敏，
手指放大时候感觉有点跳动，容易返回

**Comment by yangchaojiang** [comment]
你的手机太小吧， 设置值台下哦， 容易误触发的

**Comment by INTKILOW** [comment]
设置值台下？

**Comment by yangchaojiang** [comment]
目前没有开放

**Comment by yangchaojiang** [comment]
我看看好不好加

**Comment by INTKILOW** [comment]
手指放大时候感觉有点跳动,还有那个拖拽感觉容易触发长按

**Comment by yangchaojiang** [comment]
这个没法十细分的，有的人长安后，在拖动。

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/69300885-700be980-0c4f-11ea-9993-19e6df485928.png)
我记得有设置，
第二个参数

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/69301063-f6c0c680-0c4f-11ea-9653-da547d2517de.png)
我记得有设置， 最近忙 忘了

**Comment by INTKILOW** [comment]
en ,就是感觉预览回到原来的view上时候有点跳动，感觉像是缩放方式不一样centerCrop

**Comment by yangchaojiang** [comment]
centerCrop  自己换一下
