### ISSUE TITLE
NullPointerException崩溃

### ISSUE THREAD

**Issue by EATEATEAT** [yangchaojiang/ZoomPreviewPicture#138]
![image](https://user-images.githubusercontent.com/16115092/69206803-b6e2dc00-0b88-11ea-9a54-f06356be337d.png)
预览大图 ，拖动关闭大图，再次打开大图，点击大图返回，返回上一个activity就会有空指针

**Comment by yangchaojiang** [comment]
好好谢谢反馈

**Comment by yangchaojiang** [comment]
下午发布版本

**Comment by yangchaojiang** [comment]
试试2.2.8
