### ISSUE TITLE
同一个视频每次重新播放的时候都会重新加载，有没有设置缓存呢？谢谢。

### ISSUE THREAD

**Issue by Danniel-yan** [yangchaojiang/ZoomPreviewPicture#139]

**Comment by yangchaojiang** [comment]
视频播放页面完全自定义，本库是图片预览，不是视频， demo 实例说明，如何实现自己视频播放页面。
框架都是给出来拓展接口， 去自己想要的效果，
什么需求都给你写好，等着你来用，框架默认实现常用需求。
不常见给出来的拓展性，在自己想要需求。

**Comment by Danniel-yan** [comment]
......
