### ISSUE TITLE
大图问题SubsamplingScaleImageView

### ISSUE THREAD

**Issue by devishell** [yangchaojiang/ZoomPreviewPicture#141]
可以集成SubsamplingScaleImageView解决加载大图卡顿问题吗

**Comment by arronvera** [comment]
+1建议接入SubsamplingScaleImageView

**Comment by yangchaojiang** [comment]
不要直接加载原图好么。 图片处理最好的photoview 缩放处理 没有之一

**Comment by dylanZk1** [comment]
> 不要直接加载原图好么。 图片处理最好的photoview 缩放处理 没有之一

可是你内置了PhotoView又把自定义类封装了，然后一些例如最大最小缩放比例这些好用的属性你又不放出来，这对使用jar的人其实并不友好，建议可以把photoView的属性暴露一部分接口出来

**Comment by dylanZk1** [comment]
> 不要直接加载原图好么。 图片处理最好的photoview 缩放处理 没有之一

而且这么说吧，PhotoView根本没法完美处理所有的大图，尤其是长宽比非常夸张的图片，一旦做压缩处理后，如果不用SubsamplingScaleImageView，那个图片根本糊的不行
