### ISSUE TITLE
BasePhotoFragment 横竖屏自动切换会崩溃

### ISSUE THREAD

**Issue by devishell** [yangchaojiang/ZoomPreviewPicture#142]

**Comment by yangchaojiang** [comment]
我已经强制竖屏

**Comment by devishell** [comment]
打开手机自动旋转，我下载的demo和我自己的自定义BasePhotoFragment测试还是会崩溃

**Comment by devishell** [comment]
找到方法了，在清单文件里配置GPreviewActivity的属性android:configChanges="orientation|screenSize"
