### ISSUE TITLE
九宫格图片类型的第二次点击进去就没有进入的动画效果了

### ISSUE THREAD

**Issue by zh793060640** [yangchaojiang/ZoomPreviewPicture#15]
九宫格图片类型的第二次点击进去就没有进入的动画效果了

**Comment by yangchaojiang** [comment]
有的哦

**Comment by zh793060640** [comment]
真没有，我用两个手机试过了，第一次进入是逐渐放大变透明的，第二次进入就是瞬间放大，感觉动画像是没执行，但是调试发现动画又执行了，只是没有效果。只有九宫格类型是这样的，其他都是对的

**Comment by zh793060640** [comment]
两次都点同一个item

**Comment by yangchaojiang** [comment]
demo 是正常么。是否能截图，或者 gif 。gif 是最好，我看到你操作。我测试手机一下，都没有问题。同一个item都点10次没有问题

**Comment by zh793060640** [comment]
我录制了一个短视屏，不晓得咋个上传上来。。。

**Comment by yangchaojiang** [comment]
1007181167   你可以加我qq，视频不行，

**Comment by yangchaojiang** [comment]
版本1.1.1

**Comment by JamesGZM** [comment]
怎么样 我这边也出现进入动画没有执行的问题

**Comment by yangchaojiang** [comment]
@JamesGZM  更新demo  九宫格获取释方式示例代码。目前没有动画没有执行问题
