### ISSUE TITLE
如何实现 视频在弹出窗口中直接自动播放

### ISSUE THREAD

**Issue by lyz745704689** [yangchaojiang/ZoomPreviewPicture#152]
目前需要在弹出窗口中，手动点击播放按钮，然后重新弹出一个播放窗口；
请问，怎么可以实现，直接在第一次弹出的窗口中直接播放？

**Comment by yangchaojiang** [comment]
自定义实现视频播放页面

**Comment by lyz745704689** [comment]
大佬，我们目前的场景是，视频和图片混合在一起的，需要在弹出的查看页面中，可以直接播放视频，同时左右滑动可以切换视频和图片；

从信息流，点击视频缩略图，弹出的第一个播放页面就可以直接自定义，实现直接自动播放吗？可否讲一下大概的方法，感激不尽。

**Comment by yangchaojiang** [comment]
看demo  播放页面 完全自己自定义的

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/70406521-fdd33b80-1a7b-11ea-9f6d-61ee07a39d31.png)
****

**Comment by lyz745704689** [comment]
尝试自定义了，还是没能实现，在第一次弹出的页面中，直接播放；
目前还是只能重新打开一个页面，播放视频；让大佬见笑了；

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/70414859-3a139580-1a96-11ea-8c6b-a64cd3bc437c.png)
跳转到你的视频播放页面呀

**Comment by lyz745704689** [comment]
这样的话，视频和图片，就不能在一个页面层级播放，是吧？

**Comment by yangchaojiang** [comment]
Android   ，视频和图片。页面层级播放 费力不讨好， 你看微信视频播放都是跳页面

**Comment by lyz745704689** [comment]
非常感谢大佬详细的解答；
我做产品的，技术上不太懂；
微信上，聊天记录中有图片和视频混合的场景，点击查看时，图片和视频是可以在同一个弹出页面中进行切换并播放的；它的算是一个层级吧？我们的项目想实现的也是这种效果。

**Comment by yangchaojiang** [comment]
图片和视频 都是跳转一个新页面的。
