### ISSUE TITLE
添加一个方法让GPreviewBuilder进行携带bundle参数到自定义Activity中，自定义fragment最好能提供自定义layout方法，可以在自定义布局复制base中的主要布局进行自定义调节

### ISSUE THREAD

**Issue by jiangqinlin** [yangchaojiang/ZoomPreviewPicture#153]
/****
     *自定义预览activity 类名
     * @param className   继承GPreviewActivity
     * @param bundle  需携带的参数
     *@return GPreviewBuilder
     * **/
    public GPreviewBuilder to(@NonNull Class className,@NonNull Bundle bundle) {
        this.className = className;
        intent.setClass(mContext, className);
        intent.putExtras(bundle);
        return this;
    }

**Comment by yangchaojiang** [comment]
可以， 这个建议可以有，

**Comment by yangchaojiang** [comment]
这个需要实现自定自定义activity

**Comment by yangchaojiang** [comment]
更新了 版本 2.2.9了

**Comment by jiangqinlin** [comment]
好滴 感谢采纳！

**Comment by jiangqinlin** [comment]
好滴 感谢采纳！
