### ISSUE TITLE
自定义activity的oncreate方法没有被父类调用，需要做一下优化，demo中用的toolbar所以才生效

### ISSUE THREAD

**Issue by jiangqinlin** [yangchaojiang/ZoomPreviewPicture#154]

**Comment by yangchaojiang** [comment]
不自带toolbar 谢谢，

**Comment by yangchaojiang** [comment]
自己可以实现

**Comment by yangchaojiang** [comment]
这个是周期函数。系统自动调用的。不是我控制oncreate

**Comment by jiangqinlin** [comment]
就是我一个ImgPreviewActivity继承了GPreviewActivity，ImgPreviewActivity自定义界面有控件，我在oncreate中写点击事件无法触发onclick，我导入了整个module改了GPreviewActivity，加了个自定义继承方法在GPreviewActivity调用，在ImgPreviewActivity重写才得以让onclick生效

**Comment by yangchaojiang** [comment]
你看看的demo 我的demo 也有示例的

**Comment by jiangqinlin** [comment]
自定义activity就这一个啊
public class CustomActivity extends GPreviewActivity {
    /***
     * 重复该方法 *使用你的自定义布局
     ***/
    @Override
    public int setContentLayout() {
        return R.layout.activity_custom_preview;
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Toolbar   toolbar = (Toolbar) findViewById(R.id.toolbar);
        toolbar.setNavigationOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //退出时调用，d封装方法的 不然没有动画效果
                transformOut();
            }
        });
    }
}
没有写到另外的view点击事件，我写过，点击是无效的

**Comment by yangchaojiang** [comment]
您好，我反复测试 都是可以的

**Comment by yangchaojiang** [comment]
没有你存在无效可能

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/71950339-cd64f580-3211-11ea-82b7-51c0b9f89446.png)
