### ISSUE TITLE
显示图片的时候是从左上角显示的

### ISSUE THREAD

**Issue by scatl** [yangchaojiang/ZoomPreviewPicture#156]

**Comment by scatl** [comment]
退出的时候也是从左上角退出

**Comment by yangchaojiang** [comment]
看看demo。你的使用方式不对

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/71329912-b1502b80-2564-11ea-8f84-809e5f9e8535.png)

**Comment by yangchaojiang** [comment]
要在列表当前显示图片渲染后。明白了么。获取图片在当前屏幕的坐标，
返回才复位有动画效果。如果列表么有显示。默认左上角推出
