### ISSUE TITLE
滑动之后，再次点击返回位置恢复到左上角

### ISSUE THREAD

**Issue by wangdongi** [yangchaojiang/ZoomPreviewPicture#157]
在打开图片浏览器查看几张图片后，点击返回会出现返回的位置变为左上角，如果是第一张是正常状态，这个问题怎么解决，大神

**Comment by yangchaojiang** [comment]
你估计了解原理么，，，要在列表当前显示图片渲染后。明白了吧。获取图片在当前屏幕的坐标，
返回才复位有动画效果

**Comment by yangchaojiang** [comment]
如果列表么有显示。默认左上角推出
