### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by INTKILOW** [yangchaojiang/ZoomPreviewPicture#158]
能不能传进去一个imageview加载好的缩略图 让loading 显眼点，然后可以返回
https://github.com/iielse/ImageWatcher 类似这种处理

**Comment by yangchaojiang** [comment]
???? 你是想要loading 改变 还是imageview？

**Comment by INTKILOW** [comment]
gif可以拖动，未加载完成可以返回，我看他是先把当前imageview（已经显示的缓存）传了进去

**Comment by yangchaojiang** [comment]
gif  禁止拖动，体验不行，俩个库实现的思路都不一样。

**Comment by INTKILOW** [comment]
未加载完成可以返回?（已经显示的缓存）传了进去

**Comment by yangchaojiang** [comment]
不能哦。不过自己自定义activity。推荐显示放缩略图，加载快，原图通过 按钮实现

**Comment by yangchaojiang** [comment]
2.3.0版本 可以返回
