### ISSUE TITLE
您好，请问怎么在自定义activity中获得当前图片的currentIndex？

### ISSUE THREAD

**Issue by arronvera** [yangchaojiang/ZoomPreviewPicture#159]

**Comment by yangchaojiang** [comment]
getIntent就行

**Comment by yangchaojiang** [comment]
清问你初始化还是？

**Comment by yangchaojiang** [comment]
viewPager.getCurrentItem()  可以获取

**Comment by yangchaojiang** [comment]
2.3.1版本  可以取到 currentIndex 我改成父类继承可以用

**Comment by arronvera** [comment]
> 2.3.1版本 可以取到 currentIndex 我改成父类继承可以用

  int index=getViewPager().getCurrentItem();

这样是吧，谢谢作者大大。

**Comment by yangchaojiang** [comment]
直接用currentIndex 就行

**Comment by arronvera** [comment]
> 直接用currentIndex 就行

好的，蟹蟹~~~
