### ISSUE TITLE
在fragment和activity中，IThumbViewInfo设置bounds无效

### ISSUE THREAD

**Issue by lylelqc** [yangchaojiang/ZoomPreviewPicture#160]
如题，我是直接获取imageview的上下左右边距设置的，好像left有效，top无效，是因为用了immersionbar的原因吗？一时不知道怎么办，请问要怎么解决，谢谢@yangchaojiang 

看日志有打印这个：
PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more.

**Comment by yangchaojiang** [comment]
还有模式呀 具体看demo代码哦 实现哦

**Comment by yangchaojiang** [comment]
.setType(GPreviewBuilder.IndicatorType.Dot)//指示器类型

**Comment by yangchaojiang** [comment]
消息回复不及时哈 过年
