### ISSUE TITLE
滑动退出   空指针

### ISSUE THREAD

**Issue by onepiece0613** [yangchaojiang/ZoomPreviewPicture#169]
java.lang.NullPointerException: Attempt to invoke virtual method 'void uk.co.senab2.photoview2.PhotoViewAttacher.setOnViewTapListener(uk.co.senab2.photoview2.PhotoViewAttacher$OnViewTapListener)

**Comment by fuxianwen** [comment]
我也是 ...解决了吗

**Comment by yangchaojiang** [comment]
使用版本是多少

**Comment by fuxianwen** [comment]
> 使用版本是多少

2.3.2

**Comment by yangchaojiang** [comment]
使用android 版本是

**Comment by fuxianwen** [comment]
> 使用android 版本是

1.0

**Comment by fuxianwen** [comment]
10.0

**Comment by fuxianwen** [comment]
> 使用android 版本是

我使用哪个版本都是 进去一直加载进度条..图片是加载出来了 返回就报这个错

**Comment by yangchaojiang** [comment]
10 改很多的放东西， 我今天看一下

**Comment by yangchaojiang** [comment]
2.3.4 版本也不行？

**Comment by fuxianwen** [comment]
> 2.3.4 版本也不行？

2.3.4可以 可是为啥一直有个loading....

**Comment by yangchaojiang** [comment]
那你没有设置回调吧接口，
![图片](https://user-images.githubusercontent.com/13806413/79532333-56a88580-80a7-11ea-9d1f-3125944c5745.png)
你要回调给我

**Comment by fuxianwen** [comment]
> 那你没有设置回调吧接口，
> ![图片](https://user-images.githubusercontent.com/13806413/79532333-56a88580-80a7-11ea-9d1f-3125944c5745.png)
> 你要回调给我

感谢解答

**Comment by yangchaojiang** [comment]
好了嘛
