### ISSUE TITLE
nullPointerException with BasePhotoFragment

### ISSUE THREAD

**Issue by riozhao** [yangchaojiang/ZoomPreviewPicture#170]
I have read the source code of BasePhotoFragment, and did not find the calling of String.toLowerCase.

![image](https://user-images.githubusercontent.com/2511307/80779113-3b587280-8b9d-11ea-849f-cbf2590a89de.png)

**Comment by yangchaojiang** [comment]
![图片](https://user-images.githubusercontent.com/13806413/80897475-928c4d80-8d2b-11ea-907e-1bb19ba2aa78.png)
Hello, is there a value in the field url of the image resource? Get data is empty, the field data is empty

**Comment by rioshzhao** [comment]
Thanks for your advice!  I have found the code that may cause the crash.
