### ISSUE TITLE
大佬 自定义Activity不能用setSupportActionBar(toolbar)

### ISSUE THREAD

**Issue by liangzemian** [yangchaojiang/ZoomPreviewPicture#174]
大佬 可以把GPreviewActivity继承的FragmentActivity升级成AppCompatActivity吗，现在不能在自定义Activity里面 setSupportActionBar(androidx.appcompat.widget.Toolbar)

**Comment by yangchaojiang** [comment]
不能。 使用AppCompatActivity 需要引用v7，造成库体积增大。AppCompatActivity 没法使用FragmentActivity的特性，
