### ISSUE TITLE
PhotoViewAttacher闪退

### ISSUE THREAD

**Issue by zt80hou** [yangchaojiang/ZoomPreviewPicture#182]
![image](https://user-images.githubusercontent.com/10629437/91539752-6042d380-e94c-11ea-81f0-8e6e3e96aaab.png)

**Comment by yangchaojiang** [comment]
版本2.3.6已修复

**Comment by zt80hou** [comment]
辛苦

**Comment by zt80hou** [comment]
> 版本2.3.6已修复

辛苦了
