### ISSUE TITLE
crash : java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by songtao542** [yangchaojiang/ZoomPreviewPicture#185]
12-11 16:31:31.298 20286 20286 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at com.previewlibrary.wight.SmoothImageView.initTransform(SmoothImageView.java:483)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at com.previewlibrary.wight.SmoothImageView.onDraw(SmoothImageView.java:99)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:22218)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21095)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:21950)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4445)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4206)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:22221)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21095)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:21950)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4445)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4206)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:22221)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21095)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:21950)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4445)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4206)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:22221)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21095)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:21950)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4445)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4206)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21086)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:21950)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4445)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4206)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21086)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:21950)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4445)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4206)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.draw(View.java:22221)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at com.android.internal.policy.DecorView.draw(DecorView.java:808)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:21095)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3837)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3565)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2849)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1756)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7844)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1043)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:801)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1028)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7484)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-11 16:31:31.298 20286 20286 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by yangchaojiang** [comment]
参考demo代码，的图片没有没有指定宽高
