### ISSUE TITLE
初始化的时候Glide方法不存在

### ISSUE THREAD

**Issue by ShunjieJia** [yangchaojiang/ZoomPreviewPicture#19]
别的依赖有Glide4.0然后初始化的时候Glide.into(new SimpleTarget<Bitmap>() 的方法就不行了，怎么解决啊，新手求带

**Comment by yangchaojiang** [comment]
4.0的GlideApp 使用，。不是Glide 
4.0 gilde 使用文档https://muyangmin.github.io/glide-docs-cn/

**Comment by ShunjieJia** [comment]
![tim 20171024181340](https://user-images.githubusercontent.com/22089221/31937867-59edb348-b8e8-11e7-98c2-a74f1e4cc4c0.png)

不是Glide初始化的问题，是Glide.into（）里面的回调的问题

**Comment by yangchaojiang** [comment]
具体你的参看gilde4.0用法 我的只是demo 示例哦， 4.0 和3.7api 和发用 差异的，你按照4.0 api 做

**Comment by ShunjieJia** [comment]
![tim 20171025090331](https://user-images.githubusercontent.com/22089221/31975428-c875e210-b963-11e7-971a-e9d033a28766.png)
非常感谢您，昨天也是按照4.0这么写的，不过可能实现方法没有自动实现onLoadStarted,所以没能跳转到大图界面，现在已经好了，再次感谢大神
