### ISSUE TITLE
GPreviewActivity中fragment数量的问题

### ISSUE THREAD

**Issue by webbin** [yangchaojiang/ZoomPreviewPicture#21]
你好，我看到你在demo里用的图片是网络图片，关键是居然有600多个链接，直接把这么多连接传过去然后建了600多个fragment，这样不会有性能问题吗？（我应该没理解错吧，GPreviewActivity初始化的时候新建了几百个PhotoFragment）是不是应该考虑更安全更节省资源的方式呢？

**Comment by yangchaojiang** [comment]
嘿嘿，可以考虑在adapter ，我用静态方法new 的 相对没有压力那么大

**Comment by yangchaojiang** [comment]
改用静态方法调用
![tim 20171108151226](https://user-images.githubusercontent.com/13806413/32536002-5b3203ac-c497-11e7-9cac-ee3ecf966c7c.png)
14到17.5内存  1170个 
![tim 20171108151240](https://user-images.githubusercontent.com/13806413/32536007-6307cdbe-c497-11e7-8540-ef52eccd77c0.png)
  30个  14到16.6内存   相差1m内存  相对手机
这个结果可以满意么。

**Comment by webbin** [comment]
@yangchaojiang 原来如此，受教了
