### ISSUE TITLE
这样就不能写长按事件了

### ISSUE THREAD

**Issue by yefangqingchen** [yangchaojiang/ZoomPreviewPicture#22]
这样就不能写长按事件了，依赖之后怎么做长按 ？

**Comment by yangchaojiang** [comment]
？？？那个长按

**Comment by yefangqingchen** [comment]
没事了，我改了下你的代码，就是图片长按下载，开始我是直接依赖的没下载

发自我的 iPhone

在 2017年11月14日，15:39，yangchaojiang <notifications@github.com<mailto:notifications@github.com>> 写道：


？？？那个长按

**Comment by yefangqingchen** [comment]
对了可以停止旋转吗，就是不跟着手势移动

发自我的 iPhone

在 2017年11月14日，15:39，yangchaojiang <notifications@github.com<mailto:notifications@github.com>> 写道：


？？？那个长按

**Comment by yangchaojiang** [comment]
photoview 手势你这个库。我集成的

**Comment by ShunjieJia** [comment]
图片长按下载能不能给我看看，我也在做这个 @yefangqingchen

**Comment by yefangqingchen** [comment]
代码发你了，改改就可以了


________________________________
发件人: 贾顺杰 <notifications@github.com>
发送时间: 2017年11月15日 6:57
收件人: yangchaojiang/ZoomPreviewPicture
抄送: 夜方轻尘; Mention
主题: Re: [yangchaojiang/ZoomPreviewPicture] 这样就不能写长按事件了 (#22)


图片长按下载能不能给我看看，我也在做这个 @yefangqingchen<https://github.com/yefangqingchen>

―

**Comment by ShunjieJia** [comment]
发到哪里了，大神 @yefangqingchen

**Comment by yefangqingchen** [comment]
附件里面有啊，我把整个类都发你了


________________________________
发件人: 贾顺杰 <notifications@github.com>
发送时间: 2017年11月15日 9:37
收件人: yangchaojiang/ZoomPreviewPicture
抄送: 夜方轻尘; Mention
主题: Re: [yangchaojiang/ZoomPreviewPicture] 这样就不能写长按事件了 (#22)


发到哪里了，大神 @yefangqingchen<https://github.com/yefangqingchen>

―

**Comment by ShunjieJia** [comment]
可以再给我发一遍吗？我确实没收到邮件，邮箱是：jiashunjie1001@163.com

**Comment by ShunjieJia** [comment]
![tim 20171116111822](https://user-images.githubusercontent.com/22089221/32872184-5a6c04f2-cac0-11e7-8a75-2199080b7fe6.png)

**Comment by yangchaojiang** [comment]
@yefangqingchen @ShunjieJia 😂😂😂😂😂😂

**Comment by ShunjieJia** [comment]
不太会用Github，采用了没多久

**Comment by yefangqingchen** [comment]
发了


________________________________
发件人: 贾顺杰 <notifications@github.com>
发送时间: 2017年11月16日 3:24
收件人: yangchaojiang/ZoomPreviewPicture
抄送: 夜方轻尘; Mention
主题: Re: [yangchaojiang/ZoomPreviewPicture] 这样就不能写长按事件了 (#22)


不太会用Github，采用了没多久

―

**Comment by ShunjieJia** [comment]
嗯嗯，收到了，非常感谢

**Comment by yangchaojiang** [comment]
增加 图片预览页面拓展。实现长按。添加自己布局样式等。详情查看2.0.0 注意新版本采用引用名称！ @yefangqingchen @ShunjieJia
