### ISSUE TITLE
怎么禁用图片的拖拽

### ISSUE THREAD

**Issue by yefangqingchen** [yangchaojiang/ZoomPreviewPicture#25]
怎么禁用图片的拖拽 ？
因为拖拽有适配问题，有得手机又问题

**Comment by yangchaojiang** [comment]
？？？退出吗？

**Comment by yangchaojiang** [comment]
可以加上这个字段

**Comment by yangchaojiang** [comment]
明天新版本，由于采用引用的名称 现在审核中

**Comment by yefangqingchen** [comment]
好明天看看

发自我的 iPhone

在 2017年11月22日，19:23，yangchaojiang <notifications@github.com<mailto:notifications@github.com>> 写道：


明天新版本，由于采用引用的名称 现在审核中

**Comment by yefangqingchen** [comment]
我今天看了下你更新的代码，你添加了 禁止拖拽。


 可能你改了什么东西，我发现一个问题。


 第一次双击图片放大一次，第二次双击图片在放大一次，当第三双击的时候图片应该回到原有的大小，你这个没有返回原有大小，需要在点击一次。你看看吧。


所以我又回到了你的上一个版本，在上一个版本上自己添加了禁止拖拽事件。




________________________________
发件人: 夜方 轻尘 <yefangqingchen@hotmail.com>
发送时间: 2017年11月22日 11:24
收件人: yangchaojiang/ZoomPreviewPicture
主题: Re: [yangchaojiang/ZoomPreviewPicture] 怎么禁用图片的拖拽 (#25)

好明天看看

发自我的 iPhone

在 2017年11月22日，19:23，yangchaojiang <notifications@github.com<mailto:notifications@github.com>> 写道：


明天新版本，由于采用引用的名称 现在审核中

―

**Comment by yangchaojiang** [comment]
哪个phoview的效果，增加缩小的最小值0.8的原来的
