### ISSUE TITLE
图片进入动画问题

### ISSUE THREAD

**Issue by JamesGZM** [yangchaojiang/ZoomPreviewPicture#26]
![image](https://user-images.githubusercontent.com/17449136/33642137-845be616-da73-11e7-9eb9-2e661023f8b3.png)
这个部分把Activity实例传入 
![image](https://user-images.githubusercontent.com/17449136/33642172-a243aaf6-da73-11e7-9753-2533f91dc936.png)
同时我在自己的Activity的基类进行重写动画 
![image](https://user-images.githubusercontent.com/17449136/33642199-bb22165c-da73-11e7-9770-42b43394b066.png)
这样就会把进入动画覆盖
我的解决方案是
![image](https://user-images.githubusercontent.com/17449136/33642218-d79bb036-da73-11e7-949c-673ec8b4725c.png)
消除跳转动画
建议在
![image](https://user-images.githubusercontent.com/17449136/33642223-e7ac5962-da73-11e7-832f-246782df018c.png)
这行下面加入

**Comment by yangchaojiang** [comment]
哦哦。，原来你是重写activity方法。谢谢你建议

**Comment by yangchaojiang** [comment]
2.0.1
