### ISSUE TITLE
我给你的demo下下来报了三次数组越界

### ISSUE THREAD

**Issue by perrrfeck** [yangchaojiang/ZoomPreviewPicture#27]
java.lang.IndexOutOfBoundsException: Invalid index 57, size is 0
                                                                                at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                at java.util.ArrayList.get(ArrayList.java:308)
                                                                                at com.previewlibrary.GPreviewActivity$2.onGlobalLayout(GPreviewActivity.java:165)

**Comment by yangchaojiang** [comment]
你是点击那个我修改 demo 实例代码。demo没有修改改好。

**Comment by yangchaojiang** [comment]
你是点击那个报错，  最近我修改 demo 实例代码。

**Comment by yangchaojiang** [comment]
我最近demo我全部点击都是没有问题，我demo重新上传一下。

**Comment by yangchaojiang** [comment]
谢谢你支持。

**Comment by perrrfeck** [comment]
我有给你发报错的信息 你可以看下

**Comment by yangchaojiang** [comment]
代码没有问题哦。我刚才测试过

**Comment by yangchaojiang** [comment]
只能已经显示在屏幕中图片，有还原动画。
屏幕外左上角是默认动画退出。

**Comment by perrrfeck** [comment]
你发下你QQ或微信吧  这个库是我今天才下下来的  刚刚加你的库还遇到个问题  我QQ 229798376

**Comment by yangchaojiang** [comment]
你加判断哦，不是图片，就不要写入图片预览数据中

**Comment by perrrfeck** [comment]
Error:Execution failed for task ':main_projects:LittleAnt_Teacher:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: uk/co/senab/photoview/Compat.class
项目里已经有photoview了   引入你这个问题该怎么处理 -。-

**Comment by yangchaojiang** [comment]
compile('com.ycjiang:ImagePreview:2.0.1', {
        exclude group: 'com.github.chrisbanes.photoview', module: library'
    })
移除我库里版本。对其你版本

**Comment by perrrfeck** [comment]
不好意思  这块不太会写 photoview是个jar包

**Comment by yangchaojiang** [comment]
😂 😂 😂 😹 ....android studio 都是远程引用啊，删除jar 改远程引用哦
