### ISSUE TITLE
Samsung SM-G9009W手机加载图片大图全黑

### ISSUE THREAD

**Issue by afunnyrainman** [yangchaojiang/ZoomPreviewPicture#28]
你好，Samsung SM-G9009W手机加载图片大图全黑，图片是有的Bitmap也不是null

**Comment by afunnyrainman** [comment]
IZoomMediaLoader中GLIDE加载成功onResourceReady

              if(BasePhotoFragment.this.imageView.getTag().toString().equals(BasePhotoFragment.this.beanViewInfo.getUrl())) {
                    BasePhotoFragment.this.imageView.setImageBitmap(bitmap);
                    BasePhotoFragment.this.loading.setVisibility(8);
                }

loading隐藏了 但是为什么setImageBitmap不好使，并且bitmap还飞Null

**Comment by yangchaojiang** [comment]
？？？？请问你配置加载图片管理类么？

**Comment by afunnyrainman** [comment]
TestImageLoader implements IZoomMediaLoader 配置了，别的手机没有问题

**Comment by yangchaojiang** [comment]
加载出错。断点调试，你加载图片相应缩放处理，

**Comment by afunnyrainman** [comment]
你加载图片相应缩放处理，是什么意思。

**Comment by yangchaojiang** [comment]
gilde 设置哦，图片缩放大小等 。

**Comment by afunnyrainman** [comment]
重置宽高这个手机就出来了，请问这是为什么。

**Comment by yangchaojiang** [comment]
原因很多。图片太大，有时手机上，gilde 是加载不出来，有时自己处理文件大小。我以前在op vivo 手机出现类似问题，

**Comment by afunnyrainman** [comment]
好的，谢谢。

**Comment by yangchaojiang** [comment]
记得star支持一下。:smiley::smiley:

**Comment by afunnyrainman** [comment]
好久前就star了，还follow了。上回我提问过你可能忘记我啦。

**Comment by yangchaojiang** [comment]
😂
