### ISSUE TITLE
能不能改变下访问网络图片的加载动画

### ISSUE THREAD

**Issue by yueyingsk** [yangchaojiang/ZoomPreviewPicture#30]
加载中动画应该在图片加载器里面而不是在外面

**Comment by yangchaojiang** [comment]
？？？？

**Comment by yangchaojiang** [comment]
？？？能在描述详细一点么？

**Comment by yueyingsk** [comment]
就是页面上显示的是缩略图，点击时候访问的是真正的地址，这时候需要加载嘛然后加载动画就是在直接在页面上一个圈在转，我建议加载中的动画应该在图片浏览器里展现，进度完毕展示大图 @yangchaojiang

**Comment by yangchaojiang** [comment]
你可以自定义Fragment 你想要操作。开放权限的

**Comment by yueyingsk** [comment]
@yangchaojiang 但是现在是只要是直接加载网络图片，就会先出来一个加载的圈在转的动画，然后图片下载完之后才会显示图片加载器，这个加载的动画怎么关闭呢？

**Comment by yangchaojiang** [comment]
你可以自定义Fragment  重写我方法，就行
