### ISSUE TITLE
图片数据是否支持多种

### ISSUE THREAD

**Issue by shingohu** [yangchaojiang/ZoomPreviewPicture#31]
比如URL base64 本地 或者直接drawable等

**Comment by yangchaojiang** [comment]
框架本身不对uri  处理，支不支持  决定你图片加载框架。

**Comment by elmliu** [comment]
> 框架本身不对uri 处理，支不支持 决定你图片加载框架。

您好，我也有这个问题。框架虽然不对url处理，但是自定义加载接口返回的已经是图片的url信息了，如下<br/>
个人拙见会不会返回自定义数据对象更好一些呢

**Comment by elmliu** [comment]
> 框架本身不对uri 处理，支不支持 决定你图片加载框架。

您好，我也有这个问题，虽然框架不对url处理，但是自定义加载接口返回的已经是url信息了，如下
```ZoomMediaLoader.getInstance().getLoader().displayImage(this, beanViewInfo.getUrl(), imageView, mySimpleTarget);```
个人拙见，在这里会不会返回自定义数据对象更好一些呢

**Comment by yangchaojiang** [comment]
这个回调对象没用，这个只是需要uri的使用。
其他字段多余的，业务场景用不到
