### ISSUE TITLE
不能设置最小缩放尺寸，且单击的时候会有图片抖动的问题

### ISSUE THREAD

**Issue by lyz745704689** [yangchaojiang/ZoomPreviewPicture#35]
希望大神能看下这个问题，谢谢

**Comment by yangchaojiang** [comment]
尼自定义framgent 集成我父类，拿到image控件。自己设置，最小缩放尺寸

**Comment by lyz745704689** [comment]
先谢过，请问，单击的时候，容易识别成拖动，造成图片抖动，该如何解决呢？

**Comment by lyz745704689** [comment]
正在用您这个做项目，遇到几个小问题，不知道大神有没有时间帮忙解答一下，我微信：just_do111  万分感激

**Comment by yangchaojiang** [comment]
容易识别成拖动  每个人手感不一样。这个需要项目下载自己修改参数大小，本地依赖。
