### ISSUE TITLE
当用手指缩放或放大操作图片后，就无法再向上或者向下滑动关闭图片了。

### ISSUE THREAD

**Issue by luddite1989** [yangchaojiang/ZoomPreviewPicture#37]
当用手指缩放或放大操作图片后，就无法再向上或者向下滑动关闭图片了。，小米MIX2 7.1系统

**Comment by yangchaojiang** [comment]
请还原初始化大小。

**Comment by luddite1989** [comment]
请问如何还原？用手指拖动吗？没用。

**Comment by yangchaojiang** [comment]
photoview 控件你都不熟悉么？双击就还原了。。

**Comment by luddite1989** [comment]
我熟悉有用么？你做给用户的还是做给开发的？何况我这边手机双击并不能还原，只会放大或缩小。单击一下才会还原。我是不是要toast一下给用户，你需要单击一下还原？

**Comment by yangchaojiang** [comment]
图片缩放处理，我不是控制，photoview本身的功能。你要修改操作的哈，可以自定义fragment 实现你想要的
