### ISSUE TITLE
关于Activity和Fragment扩展性问题

### ISSUE THREAD

**Issue by q460468765** [yangchaojiang/ZoomPreviewPicture#38]
1、Fragment的loading样式怎么修改，感觉扩展性不强，为什么不直接设置protected，能够让自定义的Fragment获取到这个控件进行更改
2、我以自己写的九宫格图片展示，传currentPosition会有很多未知的问题，第一次进入时dot点的位置很乱，需要左右切换viewpager时才正常
这个图，Position = 4，但是刚进去的时候是这样展示的，开始滑动后就正常了
![image](https://user-images.githubusercontent.com/8463776/35148389-e96c5012-fd4c-11e7-8d66-fc82b56a126e.png)

**Comment by q460468765** [comment]
`GPreviewBuilder.from(ImageDetailsActivity.this)
                            .setData(picPreviewBeans)
                            .setCurrentIndex(position)
                            .setUserFragment(PicPreviewFragment.class)
                            .setSingleFling(true)//是否在黑屏区域点击返回
                            .setDrag(true)//是否禁用图片拖拽返回
                            .setType(GPreviewBuilder.IndicatorType.Dot)
                            .start();//启动`

**Comment by yangchaojiang** [comment]
谢谢反馈，完了提供get或者protected。
指示器采用别人作者的。我会排查的

**Comment by yangchaojiang** [comment]
已经修复的2.0.5   指示器作者新库有问题，我还原了。控件已经是protected
