### ISSUE TITLE
请教一个动画时长问题？

### ISSUE THREAD

**Issue by zt80hou** [yangchaojiang/ZoomPreviewPicture#41]
TRANSFORM_DURATION = 300 ，修改这个参数，动画快慢没啥变化，甚至as.setDuration(TRANSFORM_DURATION);  animator.setDuration(TRANSFORM_DURATION); 都注释掉，动画快慢还是没啥变化。我用了官方的Zoom Demo，改时长明显有快慢变化，请教一下您这个项目如何控制动画快慢？

**Comment by yangchaojiang** [comment]
目前没有开放动画时间。。。。

**Comment by zt80hou** [comment]
希望下个版本可以开放，我们测试提了一个BUG，感觉动画慢，延期处理。

**Comment by yangchaojiang** [comment]
2.0.9 版本setDuration
