### ISSUE TITLE
请教一个图片缩放归位时卡顿的问题

### ISSUE THREAD

**Issue by lyz745704689** [yangchaojiang/ZoomPreviewPicture#42]
图片查看时，我做了全屏处理；这时候在退出图片查看，在图片缩放到原来的位置时，会卡顿一下，请教大佬该如何解决？谢谢。

**Comment by lyz745704689** [comment]
应该是全屏处理了，图片查看时，与之前上移了一个状态栏的高度，图片回到小图时，与原来的位置偏移了一个状态栏的高度，可是怎么解决呢，大佬？先谢了，求解答

**Comment by yangchaojiang** [comment]
在循环添加托坐标时，加上你状态栏高度 试一下。

**Comment by lyz745704689** [comment]
多谢解答，解决了；不过有一点不完美，点击返回键时，图片会先下移一个状态栏的距离，然后缩放到原来的位置。

**Comment by yangchaojiang** [comment]
那你也可以预览activity 做成全屏处理，沉浸下。支持自定义activity

**Comment by lyz745704689** [comment]
多谢了，我去试一下。
