### ISSUE TITLE
代码运行报错，提示缺少PhotoView

### ISSUE THREAD

**Issue by risechen** [yangchaojiang/ZoomPreviewPicture#44]
![image](https://user-images.githubusercontent.com/31931021/36852716-66474888-1da7-11e8-8afa-c852c6ca7d21.png)

**Comment by yangchaojiang** [comment]
你是不是高版本PhotoView 吗？ 版本对齐吗？？

**Comment by QinCM** [comment]
版本对齐是什么意思？

**Comment by yangchaojiang** [comment]
你可以查看类库代码哦。

**Comment by yangchaojiang** [comment]
@QinCM  对齐就是，你一个项目引用多个三方库，有的三方库引用到同一个类库，版本不一样。
然后所有对齐同一个版本里。
