### ISSUE TITLE
动画时长问题

### ISSUE THREAD

**Issue by zt80hou** [yangchaojiang/ZoomPreviewPicture#45]
![image](https://user-images.githubusercontent.com/10629437/36878987-7a635cbc-1dfc-11e8-91bb-299dced2eb42.png)

![image](https://user-images.githubusercontent.com/10629437/36878881-fb1d6dbc-1dfb-11e8-8f0a-19447c952e73.png)
动画时长类型不匹配，没有效果

**Comment by yangchaojiang** [comment]
是有效果，那是默认值。 2000  好 200 一看都看出来哦

**Comment by zt80hou** [comment]
为啥是boolean类型 不合理啊

**Comment by yangchaojiang** [comment]
我的我的:joy::joy::joy::joy:

**Comment by yangchaojiang** [comment]
2.1.0 版本

**Comment by zt80hou** [comment]
完美
