### ISSUE TITLE
[改进建议] 

### ISSUE THREAD

**Issue by jounghu** [yangchaojiang/ZoomPreviewPicture#47]
1. 能否增加一个预览删除回调？（我有时间可以写写玩玩~）
2. 个人感觉构造那个UserThumb有点麻烦，一般图像链接都是一个String或者相册的Uri，能否改进？

**Comment by yangchaojiang** [comment]
必须有这个 rect 对象，是这个本库个核心所在，动画过度。

**Comment by yangchaojiang** [comment]
预览删除回调 你可以自定义Fragment 实现你的想要操作
