### ISSUE TITLE
PhotoView包名重复

### ISSUE THREAD

**Issue by yuanmenghao** [yangchaojiang/ZoomPreviewPicture#51]
现在GitHub上的所有图片相关库都用到了photoview，为了避免冲突所有作者都把放到本地引用，但是你们好歹改一下包名啊。只要引用2个库，就会报包名重复的错误。既然都用到本地了为什么不改包名，还不如用gradle引用，好歹有个exclude可以用。你们本地包名类名重复 这就没辙了啊。只能代码下出来放我自己本地，绝望！！！！

**Comment by yuanmenghao** [comment]
好不容易下出来引用上，竟然在红米4上 手势放大报错Method 'android.graphics.Matrix uk.co.senab.photoview.PhotoViewAttacher.getD

**Comment by yangchaojiang** [comment]
,,,,,d好的。注意事件冲突了，采用本地依赖的。

**Comment by yuanmenghao** [comment]
兄弟，你用的photoview 在红米4上面手势放大的时候报错，PhotoViewAttacher 1244行，但是这个类并没有1244行。我把项目里的photoview换成了https://github.com/chrisbanes/PhotoView/，换成这个photoview后需要在你的继承photoview的自定义view里删除最后一个方法，然后就可以顺利使用了。

**Comment by yangchaojiang** [comment]
photoview 版本不止。我找到我是使用类库的photoview的类。现在同包名下的同名称文件会和并的。我下版本。包名下改一下。

**Comment by yangchaojiang** [comment]
photoview包名已经该更换，版本2.1.7
