### ISSUE TITLE
图片加载中的时候点击返回直接崩溃

### ISSUE THREAD

**Issue by yuanmenghao** [yangchaojiang/ZoomPreviewPicture#55]
如果图片还在加载中点击返回按钮的话 会直接卡死。在图片预览的时候切换到最后一张图的时候滑动退出，会有一定几率崩溃，

**Comment by yangchaojiang** [comment]
提供一下日志

**Comment by yuanmenghao** [comment]
第一个问题没有日志，第一个问题很容易复现，开启2G网，当progressbar在转的时候点返回，直接就卡死了，我在看源码还没找到是什么问题。第二个问题的日志刚才忘复制了，稍后我复制过来

**Comment by yuanmenghao** [comment]
老哥，如果图片的路径打不开或者图片还没加载出来的时候点返回，直接就卡死了。这问题很致命啊，帮忙看一下代码需要改哪里，我是下载下来用的本地lib

**Comment by yangchaojiang** [comment]
用图片加载框架如失失败就行了哦

**Comment by zt80hou** [comment]
![image](https://user-images.githubusercontent.com/10629437/43238363-849b5d92-90c0-11e8-8f38-c7e005f05167.png)
点开看大图的时候，源码禁用了返回键，必须等图片出来才可以，否则就卡住，这个问题确实不太好。

**Comment by songrui** [comment]
> 老哥，如果图片的路径打不开或者图片还没加载出来的时候点返回，直接就卡死了。这问题很致命啊，帮忙看一下代码需要改哪里，我是下载下来用的本地lib

像作者说的：用图片加载框架如失失败就行了哦

比如用glide加载图片，设置一个加载失败时的占位图就行了：
`
                Glide.with(context).load(path).apply(new RequestOptions().error(R.drawable.ic_default_pic))
                        .listener(new RequestListener<Drawable>() {
                            @Override
                            public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Drawable> target, boolean isFirstResource) {
//                                Drawable drawable = context.getResources().getDrawable(R.drawable.ic_default_pic);
//                                imageView.setImageDrawable(drawable);
                                simpleTarget.onLoadFailed(null);
                                return false;
                            }

                            @Override
                            public boolean onResourceReady(Drawable resource, Object model, Target<Drawable> target, DataSource dataSource, boolean isFirstResource) {
                                imageView.setImageDrawable(resource);
                                simpleTarget.onResourceReady();
                                return false;
                            }
                        }).into(imageView);`
