### ISSUE TITLE
怎么自定义下拉拖拽的距离

### ISSUE THREAD

**Issue by Zerbaoo** [yangchaojiang/ZoomPreviewPicture#56]
现在是拖拽超过半个屏幕的距离图片才会缩放返回
怎么自定义下拉拖拽的距离？

**Comment by Zerbaoo** [comment]
还是单独写一个方法比较好

**Comment by protectedMan** [comment]
主要考虑到不设置isdrag，单独设置sensitivity是没有意义的。isdrag和sensitivity是成对的属性。
