### ISSUE TITLE
闪退问题 荣耀青春8

### ISSUE THREAD

**Issue by LiChangXing** [yangchaojiang/ZoomPreviewPicture#61]
下载下来准备跑呢，闪退 Unable to instantiate application com.example.previewpicture.app.App: java.lang.ClassNotFoundException: Didn't find class "com.example.previewpicture.app.App" on path: DexPathList[[zip file "/data/app/com.example.previewpicture-yeru-yBh1jQbWv17FBfMMA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.previewpicture-yeru-yBh1jQbWv17FBfMMA==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]

**Comment by yangchaojiang** [comment]
检查你的下载项目呢， 这个路径是否存在com.example.previewpicture.app.App 文件哦
你运行报错没有找到这个类， 或者重新编译
