### ISSUE TITLE
关于自定义fragment的问题

### ISSUE THREAD

**Issue by happinesspeople** [yangchaojiang/ZoomPreviewPicture#64]
你好，请问一下有没有提供修改布局的自定义fragment，现在的demo有一个继承BasePhotoFragment但是却没有自定义view，如果我自定义fragment需要改布局，是不是除了要重写你文档说的onCreateView方法之外，还需要重写onViewCreated方法并且不能调用super.onViewCreated(view, savedInstanceState)，包括加载状态的控制等呢？
因为你在BasePhotoFragment中的onViewCreated()方法中有进行initView()和initData()的操作，我如果用自己的布局没有按照你的布局id命名就会空指针。请问方便提供一个修改布局的自定义fragment吗？

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/42566454-3dff5dc6-8539-11e8-8d00-66cc5ca51c4d.png)

**Comment by yangchaojiang** [comment]
@Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(com.previewlibrary.R.layout.fragment_image_photo_layout, container, false);
    }

**Comment by yangchaojiang** [comment]
你的布局包含我的就行

**Comment by happinesspeople** [comment]
你的意思是说在我自己自定义的layout里边include你的这个布局就行是吗？
这个我知道，但是我就是为了修改一下加载的loading的布局，你现在使用ProgressBar来实现，但是我们项目是一个自定义的view，不是ProgressBar，而你在initView()方法中有对这个ProgressBar进行获取以及控制显示隐藏，请问我如果不是使用ProgressBar需要怎么进行自定义呢？

**Comment by yangchaojiang** [comment]
把你自定义的view的id 赋值 跟 ProgressBar 的id 一样就行,   然后删除ProgressBar

**Comment by happinesspeople** [comment]
<img width="724" alt="69b70861-913c-4fe0-9b23-35ea313fb661" src="https://user-images.githubusercontent.com/23250466/42568144-b5170b34-853e-11e8-9c42-44b537663635.png">
你这个地方已经申明了loading这个字段是ProgressBar类型，而我的加载控件是一个自定义view不是继承自ProgressBar，你下边直接找到这个id的，这样不是会类型转换异常。
<img width="678" alt="d8e80682-3732-43d0-9197-8ba80b64ac8b" src="https://user-images.githubusercontent.com/23250466/42568260-1af41348-853f-11e8-8837-a06c132df42d.png">
因为我不想以module的方式集成你的项目，想通过compile方式集成，这样以后你如果有修改你的项目或是fixbug我这边才容易维护。

**Comment by happinesspeople** [comment]
好的，辛苦了，谢谢啦🙏
