### ISSUE TITLE
关于单张图片的问题

### ISSUE THREAD

**Issue by happinesspeople** [yangchaojiang/ZoomPreviewPicture#65]
你好，我又来了。使用你的框架的时候加载一张图的情况计算位置一直是0
![5463df2d4354b8c8077a45f46db2b201](https://user-images.githubusercontent.com/23250466/42631291-5b564f3c-860c-11e8-97fa-194d71dac63b.jpg)
我的计算方式是这样的，因为你的demo中并没有单张图片的情况，都是列表的情况，我计算单张图片时仿造的是你列表的实现，但是一直不成功，请问需要怎么处理？
谢谢你了。

**Comment by yangchaojiang** [comment]
有single方法哦

**Comment by yangchaojiang** [comment]
参考可以viewpager的使用

**Comment by happinesspeople** [comment]
好的，谢谢

**Comment by happinesspeople** [comment]
<img width="1102" alt="f08a19c4-83eb-4cf7-8bb1-b8071e9e0f33" src="https://user-images.githubusercontent.com/23250466/42631973-52b79064-860e-11e8-8920-e7b05a5e976d.png">

这种方式吗？

**Comment by yangchaojiang** [comment]
嗯嗯

**Comment by happinesspeople** [comment]
你好，我发现是用你的框架在加载图片的时候，会先转圈之后等加载到图片时才进行显示。这样如果是点击很大的图的时候，这个加载过程就会很久，再加上使用自定义的activity需要设置activity为透明的，这样就会出现在点击查看大图时，会出现屏幕中间会有加载的progressbar，但是界面还是会看到上一个界面，不是查看大图的界面，然后得等到图片加载完才会有动画然后背景变黑。这样子的体验不是很好，所以我想进行相应的改动，但是发现在不改你源码的情况下很难进行改动。举个例子：我想通过先显示缩略图的方式，然后当缩略图加载完并完成动画整个页面背景变黑之后，再显示progressbar，同时加载真正的原图，等原图加载完再重新赋值给imageview。如下图所示，在自定义的fragment中进行以下处理：
<img width="1314" alt="14db9f3f-4309-434e-b276-1c8d910f7307" src="https://user-images.githubusercontent.com/23250466/42638436-360cca30-8620-11e8-8ee7-885c7550357b.png">
但是由于在我重新赋值mySimpleTarget之前，父类的onViewCreated已经进行了所有初始化操作，包括initData()，所以我在这之后重新赋值mySimpleTarget是没有任何作用的。
<img width="946" alt="97e17095-48bf-4277-97f4-6b4d0cc5773c" src="https://user-images.githubusercontent.com/23250466/42638569-8f4a8e70-8620-11e8-9acb-c3ec8215d453.png">
所以我觉得你应该在base中暴露一个
<img width="665" alt="70702eef-cb57-4ad3-988f-3982db391ddb" src="https://user-images.githubusercontent.com/23250466/42638794-1df4125e-8621-11e8-9517-e74336b9469f.png">
然后在initview中进行调用，如果你需要限制按照你BasePhotoFragment中的mySimpleTarget的实例方式，你可以要求继承你的实现类来进行扩展。
当然这只是我的想法不知道是不是如此，如果可以的话还是希望大神你能够提供一个真正仿微信朋友圈先加载缩略图等动画完成再在图片浏览界面中加载真正的原图的demo。还有希望你能对我这个需求的实现给我点建议。谢谢你啦🙏

**Comment by yangchaojiang** [comment]
你可以push t提交给我
然后我这里

我合并一下

![image](https://user-images.githubusercontent.com/13806413/42667778-f9886776-867f-11e8-806c-9b510156cc2c.png)

**Comment by yangchaojiang** [comment]
不推荐直接显示原图，都是缩略图
