### ISSUE TITLE
导入项目错误

### ISSUE THREAD

**Issue by rainie941217** [yangchaojiang/ZoomPreviewPicture#67]
我的开发工具版本是2.3.3的， 项目里该修改的部分都修改了 为什么编译还是会错误， 提示Failed to resolve: com.android.support:appcompat-v7:26.1.0 我全局搜索搜索不到v7:26.1.0相关的，能问下是什么情况么

**Comment by yangchaojiang** [comment]
本库是26.0.3 版本是26编译/
