### ISSUE TITLE
 mainactivtiy 页面左右滑动会出来，这个时候向下滑动不全消失

### ISSUE THREAD

**Issue by budingts** [yangchaojiang/ZoomPreviewPicture#7]
真实情况如下：
1、就是运行demo这个，有个加载不出来的，到了那个图片页面，下滑，回到mainac，在mainac 中左侧滑入，或者右侧滑入，都会出现那个acitiviy，且会卡顿，这种情况下，只要给给个error 图片，即可，亲测

**Comment by budingts** [comment]
Glide.with(this)
                .load(imgUrl)
                .asBitmap()
                .fitCenter()
                .error(R.mipmap.load_fail)
                .placeholder(R.mipmap.load_fail)
                .into(new SimpleTarget<Bitmap>() {

**Comment by yangchaojiang** [comment]
谢谢
