### ISSUE TITLE
图片比较大时显示的问题

### ISSUE THREAD

**Issue by Markzj** [yangchaojiang/ZoomPreviewPicture#73]
大神你好，我想向你请教个问题，当图片比较大的时候，图片还没加载完，透明的activity上只能看到一个进度条，这样看起来就很难接受，请问这个有什么办法解决吗？

**Comment by yangchaojiang** [comment]
[参考](https://github.com/yangchaojiang/ZoomPreviewPicture/issues/28)
图片文件大适当缩放处理。减少读取文件时间。微信过度显示时都是缩略图不是文件原图
