### ISSUE TITLE
框架能更新下么

### ISSUE THREAD

**Issue by daidaishuiping** [yangchaojiang/ZoomPreviewPicture#74]
框架能更新下么，glide的版本你的太老了啊

**Comment by yangchaojiang** [comment]
gilde版本，不在类库里。是demo实例，你在换成你的当前版本就行了

**Comment by yangchaojiang** [comment]
gilde版本，不在类库里。是demo实例，你在换成你的当前版本就行了

**Comment by yangchaojiang** [comment]
gilde版本，不在类库里。是demo实例，你在换成你的项目使用gilde的当前版本就行了
