### ISSUE TITLE
状态栏

### ISSUE THREAD

**Issue by daidaishuiping** [yangchaojiang/ZoomPreviewPicture#75]
打开图片的时候，那个状态栏会闪动一下，会影响用户体验，能不能优化下呢？

**Comment by yangchaojiang** [comment]
状态栏是没法控制的，山洞跟手机有关。

**Comment by daidaishuiping** [comment]
不啊，把浏览图片那个状态栏隐藏了，就不会出现闪动了，就像微信那样啊，它是把状态栏隐藏了，你公开一个方法让我们自己设置是否隐藏哦
