### ISSUE TITLE
加载gif图问题

### ISSUE THREAD

**Issue by Dopedada** [yangchaojiang/ZoomPreviewPicture#76]
加载gif图时,点击事件无效,不能点击退出,也不能拖拽

**Comment by yangchaojiang** [comment]
gif 禁止拖拽和缩放。

**Comment by Dopedada** [comment]
但是点击退出这个功能好像也没了

**Comment by yangchaojiang** [comment]
返回键，目前可以返回。或者
photoView 设置  imageView.setZoomable(false); 
聂可以自定义Fragment 修改为true .  进行拖拽和缩放。
