### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by baogaolion** [yangchaojiang/ZoomPreviewPicture#78]
并没有使用自定义Activity和Fragment, 启动后报错 :
java.lang.NullPointerException: ZoomMediaLoader loader  no init

还是说必须自定义一个类似new TestImageLoader()的类在application中初始化,才能正常使用

![image](https://user-images.githubusercontent.com/3152351/43750681-15690d6e-9a2c-11e8-8708-a4a9ae4eb401.png)

**Comment by yangchaojiang** [comment]
必须定义一个类似new TestImageLoader()的类在application中初始化,才能正常使用
