### ISSUE TITLE
关于视频监听的bug

### ISSUE THREAD

**Issue by leehuan** [yangchaojiang/ZoomPreviewPicture#79]
在BasePhotoFragment 每次页面滑动，fragment 会调用onDestroyView中的release，
然后将listener 至为null ，当我第二次滑动回来后，就无法监听了!

**Comment by yangchaojiang** [comment]
谢谢反馈哈，我看看，会尽快处理

**Comment by yangchaojiang** [comment]
版本2.2.0

**Comment by leehuan** [comment]
ok

**Comment by leehuan** [comment]
我本地也这么改了 :}

**Comment by yangchaojiang** [comment]
:sweat_smile: :sweat_smile: :sweat_smile:
