### ISSUE TITLE
两个手指缩小图片，这时图片会变小，并且无法再拖动退出

### ISSUE THREAD

**Issue by zhuoshirong** [yangchaojiang/ZoomPreviewPicture#80]
双击放大，再双击有些图片会变小，并且无法再拖动退出，您好，这个问题有解决方案吗，

**Comment by yangchaojiang** [comment]
这个不是问题。拖动退出。你再点击一下。还原到原来的大小就行。拖动只支持不能缩放状态下

**Comment by zhuoshirong** [comment]
这个能不能优化一下缩小松手以后还原图片原来大小，谢谢

**Comment by yangchaojiang** [comment]
你的自定义Fragment的更改最小缩放的1就行 phohView

**Comment by zhuoshirong** [comment]
你好，我想请问一下你如何设置图片的宽度，像微信那样宽度是手机的宽，高度自适应有地方可以设置吗，谢谢

**Comment by yangchaojiang** [comment]
现在图片宽度充满的，高度自定应的

**Comment by zhuoshirong** [comment]
没有啊，我打开九宫格里面的第三个item。最后一张图片，宽度也没有充满手机机的宽度啊，一些长图也是不行的；
