### ISSUE TITLE
downLoad 下载完毕之后不呢个直接运行

### ISSUE THREAD

**Issue by wangtao2855** [yangchaojiang/ZoomPreviewPicture#83]
demo下载完毕之后我放在AndroidStudio 3.1.4版本上面不能直接运行
Failed to resolve: common
Open File
之前很多类似这样的错

**Comment by yangchaojiang** [comment]
![default](https://user-images.githubusercontent.com/13806413/46183879-8fd2a680-c305-11e8-8a57-97c74af64806.png)


根据自己错误相应搞改动
![default](https://user-images.githubusercontent.com/13806413/46183952-f657c480-c305-11e8-90b6-971e063cb3b5.png)

**Comment by wangtao2855** [comment]
The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Failed to resolve: appcompat-v7
Open File
Failed to resolve: animated-vector-drawable
Open File
Failed to resolve: support-fragment
Open File
Failed to resolve: support-compat
Open File
直接倒入报错

**Comment by yangchaojiang** [comment]
作为android。 你电脑缓存导致无法下载系统库，。你没有这个库android 的库。

**Comment by yangchaojiang** [comment]
你电脑缓存导致无法下载系统库，导致试里依赖的这些。改一下版本
