### ISSUE TITLE
gif问题

### ISSUE THREAD

**Issue by wangtao2855** [yangchaojiang/ZoomPreviewPicture#84]
gif可以支持,但是我需要需要gif第一张图片自动播放 其他不播放,并且需要一个gif角标,请大神指导 1 2

**Comment by yangchaojiang** [comment]
,并且需要一个gif角标,。自定义fragment，构建的你view

**Comment by wangtao2855** [comment]
> ，并且需要一个GIF角标。自定义片段，构建的你视图

继承你的啥.然后怎么实现?

**Comment by wangtao2855** [comment]
并且gif放大后,点击gif不会推出放大界面,图片没问题 这个算不算一个bug

**Comment by yangchaojiang** [comment]
gif 缩放处理 已经给屏蔽

**Comment by yangchaojiang** [comment]
继承怎么用。  看主页使用说明和demo代码

**Comment by taosimple** [comment]
也遇到这个问题，gif预览单击不能退出

**Comment by wangtao2855** [comment]
你给他设置一个背景图片就好.这样就OK了

**Comment by taosimple** [comment]
@wangtao2855 谢谢，秒回

**Comment by wangtao2855** [comment]
> @wangtao2855 谢谢，秒回

哈 我有qq邮件通知
