### ISSUE TITLE
 2.2.2版本BasePhotoFragment 无法获取图片的bitmap 了

### ISSUE THREAD

**Issue by protectedMan** [yangchaojiang/ZoomPreviewPicture#87]
以前的版本是有的，我可以实现长按保存图片
![image](https://user-images.githubusercontent.com/17565737/48051955-8f211000-e1e1-11e8-8937-53c41687403e.png)
2.2.2去掉了，导致我无法获取到预览的图片的bitmap了

![image](https://user-images.githubusercontent.com/17565737/48052056-d909f600-e1e1-11e8-8d08-9a526e4eb255.png)

**Comment by yangchaojiang** [comment]
查看最新demo. 哈 。现在之回调起到通知作用。

**Comment by protectedMan** [comment]
刚刚写了个
![image](https://user-images.githubusercontent.com/17565737/48055324-4d489780-e1ea-11e8-910a-ad8cb41c2d6b.png)
准备push上去的 - -

**Comment by yangchaojiang** [comment]
。。。。

**Comment by yangchaojiang** [comment]
你需要用到这个对象吗？

**Comment by protectedMan** [comment]
是的，我需要保存图片啊

**Comment by yangchaojiang** [comment]
你的推荐下载图片，图片清晰度高些。

**Comment by protectedMan** [comment]
静态图都是bitmap，但是动态图各个加载框架有不同的封装类，glide的使用的是gifdrawable。

**Comment by protectedMan** [comment]
提了个pull 请求 
你看看

**Comment by yangchaojiang** [comment]
demo 现在提供保存图片方式，原来的下载原图，

**Comment by protectedMan** [comment]
没拉下来demo
