### ISSUE TITLE
大神请教几个问题？

### ISSUE THREAD

**Issue by liuxuesong001** [yangchaojiang/ZoomPreviewPicture#90]
1.视频播放是否可以支持点击暂停和播放。
2.除了视频和图片，文档格式的自定义预览图，如何实现。
3.是否支持圆角预览。
4.可否自定义本地图片及预览。
5.音频格式显示和自定义预览。

**Comment by liuxuesong001** [comment]
嗯，好的，明白了。多谢

**Comment by yangchaojiang** [comment]
谢谢支持了
