### ISSUE TITLE
第二次调用GPreviewBuilder 不显示图片 页面卡死

### ISSUE THREAD

**Issue by haohighview** [yangchaojiang/ZoomPreviewPicture#98]
日志
PhotoViewAttacher(14668): ImageView no longer exists. You should not use this PhotoViewAttacher any more.

**Comment by yangchaojiang** [comment]
PhotoViewAttacher 应该控件的问题。有时间我看看。
你出现的什么手机上。系统版本是多少

**Comment by haohighview** [comment]
魅族16th 8.1

**Comment by yangchaojiang** [comment]
估计分包找不到文件。你可以分到一个包

**Comment by yummyChina** [comment]
图片加载失败会直接 卡死 无响应

**Comment by yangchaojiang** [comment]
是不是你回调做处理了。

**Comment by yangchaojiang** [comment]
参考[100](https://github.com/yangchaojiang/ZoomPreviewPicture/issues/100)
