### ISSUE TITLE
GPreviewBuilder.setFullscreen (true) 设置全屏 返回时有位置偏移，很诡异的偏移，希望适配一下全屏显示

### ISSUE THREAD

**Issue by PangHaHa12138** [yangchaojiang/ZoomPreviewPicture#99]
GPreviewBuilder.from((Activity)mContext)
                        .setData(list)
                        .setFullscreen(true)
                        .setCurrentIndex(position)
                        .setType(GPreviewBuilder.IndicatorType.Dot)
                        .start();//启动
设置 全屏显示 返回时有诡异的位置偏移，感觉是计算坐标时需要考虑状态栏的高度，希望能适配一下 ，多谢啦

**Comment by PangHaHa12138** [comment]
startTransform.left = thumbRect.left;
// startTransform.top = thumbRect.top - ImageUtils.getStatusBarHeight(getContext());
  startTransform.top = thumbRect.top;
全屏的问题找到解决方案了  原来是算坐标的时候把状态栏高度加进去了，去掉状态栏高度就可以实现全屏了

**Comment by yangchaojiang** [comment]
好的谢谢，的完善的 我今天加上

**Comment by yangchaojiang** [comment]
更新了你看一下

**Comment by kimlllll** [comment]
图片加载完成，进度条无法隐藏

**Comment by yangchaojiang** [comment]
@kimlllll  查看你回调处理哦
